= ruby-getoptions
David Gamba, https://github.com/DavidGamba
:version: 0.1
:idprefix:

Ruby option parser based on Perl's Getopt::Long.

image:https://badge.fury.io/rb/ruby-getoptions.svg["Gem Version", link="http://badge.fury.io/rb/ruby-getoptions"]
image:https://coveralls.io/repos/DavidGamba/ruby-getoptions/badge.svg["Coverage Status", link="https://coveralls.io/r/DavidGamba/ruby-getoptions"]
image:https://codeclimate.com/github/DavidGamba/ruby-getoptions/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/DavidGamba/ruby-getoptions"]
image:https://travis-ci.org/DavidGamba/ruby-getoptions.svg["Build Status", link="https://travis-ci.org/DavidGamba/ruby-getoptions"]

== Quick overview

1. Define your command line specification:
+
[source,ruby,subs=attributes]
----
require 'ruby-getoptions'

options, remaining = GetOptions.parse(ARGV, {
  "f|flag"      => :flag,
  "string=s"    => :string,
  "int=i"       => :int,
  "float=f"     => :float,
  "procedure"   => lambda { puts 'Hello world! :-)' },
  "help"        => lambda { print_synopsis() },
  "man"         => lambda { launch_manpage() },
  "version"     => lambda { puts 'Version is {version}' },
})
----

2. Pass cmdline arguments:
+
----
$ ./myscript non-option -f --string=mystring -i 7 --float 3.14 --p --version non-option2 -- --nothing
----

3. It will run the higher order functions that were called on the cmdline:
+
[subs=attributes]
----
Hello world!
Version is {version}
----

4. Internally it will return an array with the arguments that are not options and anything after the `--` identifier, and a Hash with the values of the options that were passed:
+
----
remaining = ['non-option', 'non-option2', '--nothing']

options   = {:flag   => true,
             :string => 'mystring',
             :int    => 7,
             :float  => 3.14}
----

== Synopsis

[source,ruby]
----
require 'ruby-getoptions'

options, remaining = GetOptions.parse(ARGV, {
  "alias|name"        => :option_with_aliases,
  "flag"              => :flag,
  "nflag!"            => :negatable_flag,
  "procedure"         => lambda { puts 'Hello world! :-)' },
  "string=s"          => :required_string,
  "int=i"             => :required_int,
  "float=f"           => :required_float,
  "o_string:s"        => :optional_string,
  "o_int:i"           => :optional_int,
  "o_float:f"         => :optional_float,
  "a_string=s@"       => :string_array,
  "a_int=i@"          => :int_array,
  "a_float=f@"        => :float_array,
  "ar_string=s@{3,5}" => :string_array_with_repeat,
  "ar_int=i@{3,5}"    => :int_array_with_repeat,
  "ar_float=f@{3,5}"  => :float_array_with_repeat,
  "h_string=s%"       => :string_hash,
  "h_int=i%"          => :int_hash,
  "h_float=f%"        => :float_hash,
  "hr_string=s%{3,5}" => :string_hash_with_repeat,
  "hr_int=i%{3,5}"    => :int_hash_with_repeat,
  "hr_float=f%{3,5}"  => :float_hash_with_repeat
}, {fail_on_unknown: true})
----

Name specification::

Unique list of names to call the option through the command line. Each alias is separated by `|`.

Argument_specification::
+
|===
|Arg specification |Arg spec options |Description

|
|
|*Flag*, Empty argument specification

|!
|
|*Negatable Flag*, *Flag* that can also be negated. Use with `--no` of `--no-`.

|= type [destype] [repeat]
a| type::  `s`, `i`, `f`
destype:: `@`, `%`.
repeat::  `{ [ min ] [ , [ max ] ] }`.
|*Required argument*, argument must be present.

|: type [destype]
a| type::  `s`, `i`, `f`
destype:: `@`
repeat::  `{ [ min ] [ , [ max ] ] }`.
a|*Optional argument*, argument will default to String `''`, Int `0`, or Float `0` if not present.

NOTE: Hash argument specification is not supported in this mode because there are no reasonable defaults to add.

|===

////
|+
|
|*Increment*

|: integer [destype]
a| destype:: `@`
a|*Optional integer with default*

|: + [destype]
a| destype:: `@`
a|*Optional with increment*, Not supported yet. Does it make sense to?
////

Options:: `fail_on_unknown`, `pass_through`.

== Description

It will take an `Array[String]` (normally `ARGV`) and a `Hash[String, Object]` (option definition) and it will return a `Hash[Symbol, Object]` (options) of the given arguments and an `Array[String]` (remaining) of the remaining arguments.

It will also excecute any _procedures_ (lamba, procedure, method) in the order their corresponding options were passsed on the command line, and only if they were passed (using the `call` method).

`GetOptions.parse` will `abort` or `fail` if the command line options could not be processed successfully (input error), or if they were defined improperly. See <<errors_exceptions,Errors and Exceptions>> for details.

[option_definition]
== Option Definition

Each _Option definition_ (one key value pair in the Hash) is composed of two elements, the key, referred to as _option specification_, and the value, referred to as _option destination_.

[source,ruby]
----
require 'ruby-getoptions'

options, remaining = GetOptions.parse(ARGV, {
  key => value, # <1>
  option_specification => option_destination # <2>
})
----
<1> Each key, value pair is called an _Option definition_.
<2> The key is the _Option specification_ and the value is the _Option destination_.

Each _option specification_ consists of two parts: the _name specification_ and the _argument specification_.

The _name specification_ contains the name of the option, optionally followed by a list of alternative names or aliases separated by vertical bar characters `|`.

The _argument specification_ contains the type of option and whether or not it takes any arguments and how many.

The _option destination_ can be either a `Symbol` or a procedure (only for Flags). If a `Symbol`, it will be the `Symbol` used to access the resulting value of the command line parameters passed. If a procedure, it will be called if the _name_ of the option was passed in the command line.

For example, for the following _option definition_:

`'entry|input=s' => :data`

The name specification is `entry` with an alias of `input`, the argument specification is `=s` (required string), and the option destination is `:data`. If either `entry` or `input` is passed on the command line, the `Symbol` `:data` will be set to the `String` argument passed with the option.

As another example, for the following _option definition_:

`'version' => lambda { puts 'Version is {version}' }`

The option name is `version`, the option specification is empty (flag), and the option destination is `lambda { puts 'Version is {version}' }`. If `version` is passed on the command line, the procedure will be called (using `call`).

== Option Specification

The full list of __option specification__'s are defined in this section.

NOTE: No option that is not passed as an argument will be touched, meaning they will be `nil`.

No option specification (Flag)::

When no option specification is given, the option is considered a flag.
+
If the _option destination_ is a `Symbol`, its value will be set to `true` if passed. The option won't be touched if not called, `nil`.
+
If the _option destination_ is a procedure (lambda, procedure, method), the procedure will be called if passed (using the `call` method).

`!` (Negatable Flag)::

The option is considered a flag that can be negated with `no` or `no-`. E.g. `foo!` can be called with `--foo` (set to `true`) as well as `--nofoo` and `--no-foo` (set to `false`). The option won't be touched if not called, `nil`.

// FIXME
// Using negation on a single letter option when bundling is in effect is pointless and will result in a warning.

////
+::

The option does not take an argument and will be incremented by 1 every time it appears on the command line. E.g. `more+` , when used with `--more --more --more`, will increment the value three times, resulting in a value of 3.
////

`= type [ desttype ] [ repeat ]` (Required argument)::

The option passed requires an argument. e.g. `--string=argument` or `--string argument`.

`: type [ desttype ]` (Optional argument)::

Like `=` , but designates the argument as optional. If omitted, an empty string will be assigned to string values options, and the value zero to numeric options.
// +
// Note that if a string argument starts with - or -- , it will be considered an option on itself.

////
`: number [ desttype ]`::

Like `:i`, but if the value is omitted, the number will be assigned.

`: + [ desttype ]`::

Like `:i`, but if the value is omitted, the current value for the option will be incremented.
////

=== Option specification parameters

``type``s::
+
--

`s`:: `String`, An arbitrary sequence of characters. It is valid for the argument to start with - or -- .

`i`:: `Integer`. An optional leading plus or minus sign, followed by a sequence of digits.

// `o`:: Extended integer, Perl style. This can be either an optional leading plus or minus sign, followed by a sequence of digits, or an octal string (a zero, optionally followed by '0', '1', .. '7'), or a hexadecimal string (0x followed by '0' .. '9', 'a' .. 'f', case insensitive), or a binary string (0b followed by a series of '0' and '1').

`f`:: Real number. For example 3.14 , -6.23E24 and so on.

--

``desttype``s::
+
--

`@`:: Specify that the option is an Array. That means that multiple appearances of the option call will push to the option array. E.g. `'opt=i@' => :int_array` with `--opt 1 --opt 3 --opt 5` will render `options[:int_array]` equal to `[1, 3, 5]`.

`%`:: Specify that the option is a Hash. That means that multiple appearances of the option call will add a key=value pair to the Hash. E.g. `'define=s%' => :defines` with `--define name=getoptions --define lang=ruby` will render `options[:defines]` equal to `{'name' => 'getoptions', 'lang' => 'ruby'`.

--

`repeat`:: specifies the number of values this option takes per occurrence on the command line. It has the format `{ [ min ] [ , [ max ] ] }`.
+
`min` denotes the minimal number of arguments.
//It defaults to 1 for options with = and to 0 for options with : , see below. Note that min overrules the = / : semantics.
+
`max` denotes the maximum number of arguments. It must be at least min.
//If max is omitted, but the comma is not, there is no upper bound to the number of argument values taken.


== Input / Output

Arguments::
1. _Arguments Array_ `Array[String]`: Normally `ARGV`, but any Array of Strings will work.
2. _Option Definition_ `Hash[String, Any]`: Where `String` is the _option specification_ and `Any`, _option destination_ can be `Symbol`, or a _procedure_ (lambda, procedure, method). See <<option_definition,Option Definition>> for details.

Returns::
1. _Options Hash_ `Map[Symbol,Any]`: where `Any` can be a `String`, `Integer`, `Float`, `Array[String]`, `Array[Integer]`, `Array[Float]` And `Hash` of `String`, `Integer` and `Float`.
2. _Remaining Array_ `Array[String]`: `Array` of non-options arguments, `pass_through` <<options>>, or any argument after the `--` identifier.

== Features

* Supports passing `--` to stop parsing arguments (everything after will be left in the `remaining` `Array[String]`).

* Multiple definitions for the same option separated by `|`. e.g. `help|man`.

* Defining what kind of argument you are passing. Currently supports `s` to pass strings, `i` to pass integers and `f` to pass float values.

* Supports both array and hash modifiers.

* Argument type checking.

* Supports calling a given procedure (lambda, procedure, method) if the option name if passed on the command line.

* Supports command line options with `=`. e.g. You can use `--string=mystring` and `--string mystring`.

[[options]]
== Options

`fail_on_unknown`:: if `true`, it will abort when an unknown option is passed on the commandline. If `false` it will _WARN_ when an unknown option is passed. Default: `false`.

`pass_through`:: disable warning on unknown option. Defalt: `false`.

[[errors_exceptions]]
== Errors and Exceptions

* For incorrect _option definitions_ in the script itself it will `fail` with `ArgumentError`.

* For user input errors, it will `abort` (`SystemExit`) with a description of what the user did wrong.

== How to install it

. Get it from rubygems:
+
`gem install 'ruby-getoptions'`

. Then test it in `irb`:

  2.1.2 :001 > require 'ruby-getoptions'
  => true
  2.1.2 :002 > options, remaining = GetOptions.parse(['world', '-t', 'hello'], {'t=s' => :test})
  => [{:test=>"hello"}, ["world"]]

. Enjoy!

== Dependencies

Ruby 1.8.7+

[[roadmap]]
== Roadmap

* Support bundling

  -l -a -c  => -lac

* Support passing values after the short option character

  -i 24  => -i24

* Make matching case insensitive.

* All other Perl's Getopt::Long goodies that seem reasonable to add!

== License

The MIT License (MIT)

Copyright (c) 2014-2015 David Gamba

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
